// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Rm-32we9dWwEacUsnoi3PmbnPt4lHP8',
    appId: '1:704515777401:web:9895938e94318029e785a8',
    messagingSenderId: '704515777401',
    projectId: 'facehub121314',
    authDomain: 'facehub121314.firebaseapp.com',
    storageBucket: 'facehub121314.appspot.com',
    measurementId: 'G-7GSKG50834',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zCquDGpMR0rOzImbNxU5rOFPTjEsAWw',
    appId: '1:704515777401:android:82e6cf057e2bede0e785a8',
    messagingSenderId: '704515777401',
    projectId: 'facehub121314',
    storageBucket: 'facehub121314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lYhaTfPB74rSIY7G1IXlPsm4RwE0rKo',
    appId: '1:704515777401:ios:0f1867c384f416e9e785a8',
    messagingSenderId: '704515777401',
    projectId: 'facehub121314',
    storageBucket: 'facehub121314.appspot.com',
    iosClientId: '704515777401-4vlaq852u07vk3b211irg4elspq2hpd1.apps.googleusercontent.com',
    iosBundleId: 'com.codehq.facehub',
  );
}
